### ISSUE TITLE
Research 

### ISSUE THREAD

**Issue by anglov** [anglov/Wilico#1]
We need to have some data for tests and presentation. Get information, where we can find it and write it here. What's more, think about way of parse and strore important information and write your ideas here. 

Możesz używać polskiego ;)

**Comment by Darkkonan** [comment]
Chciałem napisać po angielsku ale zrezygnowalem. Wiec tak  w tych paczkach od Bzdaka są pliki .xml, w których jest zawarta cała treść. Linki natomiast są w dziwnej formie ponieważ odnośniki do samej wikipedi wyglądają np. tak [[Spain|Spanish]] gdzie pierwsza nazwa jest to nazwa strony na wikipedii, a druga nazwa to jest ta wyświetlana na stronie.

**Comment by anglov** [comment]
Ok, nice.
